# library(shinytest2)
#
# test_that("{shinytest2} recording: SIconfronta_2samples", {
#   skip_on_ci()
#   skip_on_covr()
#   skip_on_cran()
#
#   shiny_app <- SIconfronta::run_app()
#
#   app <- AppDriver$new(app_dir = shiny_app,
#                        name = "SIconfronta_2samples",
#                        height = 627,
#                        width = 995)
#   app$set_inputs(`scopo-aim` = "2samples", wait_ = FALSE)
#   app$click("scopo-nextbtn")
#   app$click("scopo-yesbtn")
#   app$click("scopo-yesbtn")
#   app$upload_file(`dati-file` = "raw_2samples.csv")
#   app$click("dati-nextbtn")
#   app$click("dati-yesbtn")
#   app$click("dati-yesbtn")
#   app$set_inputs(`confronto-parameter` = "load")
#   app$set_inputs(`confronto-2samples-udm` = "N")
#   app$click("confronto-save")
#   app$set_inputs(`confronto-parameter` = "yield")
#   app$set_inputs(`confronto-2samples-udm` = "kg")
#   app$set_inputs(`confronto-2samples-tabresults` = "Medie")
#   app$set_inputs(`confronto-2samples-tabresults` = "Varianze")
#   app$set_inputs(`confronto-2samples-alternative` = "greater")
#   app$click("confronto-save")
#   app$click("confronto-nextbtn")
#   app$click("confronto-yesbtn")
#   app$click("confronto-yesbtn")
#   app$set_inputs(`report-title` = "My test report for two samples")
#   app$set_inputs(`report-description` = "My test setup.")
#   app$set_inputs(`report-discussion` = "Tests passed.")
#   app$expect_values(screenshot_args = FALSE)
#   app$stop()
# })
#
#
# test_that("{shinytest2} recording: SIconfronta_2samples_par", {
#   skip_on_ci()
#   skip_on_covr()
#   skip_on_cran()
#
#   shiny_app <- SIconfronta::run_app()
#
#   app <- AppDriver$new(app_dir = shiny_app,
#                        name = "SIconfronta_2samples_par",
#                        height = 627,
#                        width = 995)
#   app$set_inputs(`scopo-aim` = "2samples_par")
#   app$click("scopo-nextbtn")
#   app$click("scopo-yesbtn")
#   app$click("scopo-yesbtn")
#   app$upload_file(`dati-file` = "raw_1sample.csv")
#   app$click("dati-nextbtn")
#   app$click("dati-yesbtn")
#   app$click("dati-yesbtn")
#   app$set_inputs(`confronto-parameter` = "load")
#   app$set_inputs(`confronto-2samples_par-udm` = "N")
#   app$set_inputs(`confronto-2samples_par-label` = "b")
#   app$set_inputs(`confronto-2samples_par-mean` = 2.520)
#   app$set_inputs(`confronto-2samples_par-sd` = sqrt(0.12634))
#   app$set_inputs(`confronto-2samples_par-n` = 12)
#   app$click("confronto-2samples_par-submit")
#   app$set_inputs(`confronto-2samples_par-tabresults` = "Medie")
#   app$set_inputs(`confronto-2samples_par-tabresults` = "Varianze")
#   app$click("confronto-save")
#   app$set_inputs(`confronto-parameter` = "yield")
#   app$set_inputs(`confronto-2samples_par-udm` = "kg")
#   app$set_inputs(`confronto-2samples_par-mean` = 22.53333)
#   app$set_inputs(`confronto-2samples_par-sd` = 5.432004)
#   app$set_inputs(`confronto-2samples_par-n` = 6)
#   app$click("confronto-2samples_par-submit")
#   app$set_inputs(`confronto-2samples_par-tabresults` = "Medie")
#   app$set_inputs(`confronto-2samples_par-tabresults` = "Normalità")
#   app$set_inputs(`confronto-2samples_par-tabresults` = "Medie")
#   app$click("confronto-save")
#   app$click("confronto-nextbtn")
#   app$click("confronto-yesbtn")
#   app$click("confronto-yesbtn")
#   app$set_inputs(`report-title` = "My test report for two samples with distribution parameters")
#   app$set_inputs(`report-description` = "My test setup.")
#   app$set_inputs(`report-discussion` = "Tests passed.")
#   app$expect_values(screenshot_args = FALSE)
#   app$stop()
# })
#
#
# test_that("{shinytest2} recording: SIconfronta_1sample_mu", {
#   skip_on_ci()
#   skip_on_covr()
#   skip_on_cran()
#
#   shiny_app <- SIconfronta::run_app()
#
#   app <- AppDriver$new(app_dir = shiny_app,
#                        name = "SIconfronta_1sample_mu",
#                        height = 627,
#                        width = 995)
#   app$set_inputs(`scopo-aim` = "1sample_mu")
#   app$click("scopo-nextbtn")
#   app$click("scopo-yesbtn")
#   app$click("scopo-yesbtn")
#   app$upload_file(`dati-file` = "raw_1sample.csv")
#   app$click("dati-nextbtn")
#   app$click("dati-yesbtn")
#   app$click("dati-yesbtn")
#   app$set_inputs(`confronto-parameter` = "load")
#   app$set_inputs(`confronto-1sample_mu-udm` = "N")
#   app$set_inputs(`confronto-1sample_mu-label` = "ref")
#   app$set_inputs(`confronto-1sample_mu-mean` = 2.4)
#   app$click("confronto-1sample_mu-submit")
#   app$set_inputs(`confronto-1sample_mu-significance` = "0.99")
#   app$set_inputs(`confronto-1sample_mu-tabresults` = "Medie")
#   app$set_inputs(`confronto-1sample_mu-alternative` = "greater")
#   app$click("confronto-save")
#   app$set_inputs(`confronto-parameter` = "yield")
#   app$set_inputs(`confronto-1sample_mu-udm` = "kg")
#   app$set_inputs(`confronto-1sample_mu-label` = "ref")
#   app$set_inputs(`confronto-1sample_mu-mean` = 30)
#   app$set_inputs(`confronto-1sample_mu-significance` = "0.95")
#   app$set_inputs(`confronto-1sample_mu-alternative` = "different")
#   app$click("confronto-1sample_mu-submit")
#   app$click("confronto-save")
#   app$click("confronto-nextbtn")
#   app$click("confronto-yesbtn")
#   app$click("confronto-yesbtn")
#   app$set_inputs(`report-title` = "My test report for one sample and a population mean")
#   app$set_inputs(`report-description` = "My test setup.")
#   app$set_inputs(`report-discussion` = "Tests passed.")
#   app$expect_values(screenshot_args = FALSE)
#   app$stop()
# })
#
#
# test_that("{shinytest2} recording: SIconfronta_1sample_sigma", {
#   skip_on_ci()
#   skip_on_covr()
#   skip_on_cran()
#
#   shiny_app <- SIconfronta::run_app()
#
#   app <- AppDriver$new(app_dir = shiny_app,
#                        name = "SIconfronta_1sample_sigma",
#                        height = 627,
#                        width = 995)
#   app$set_inputs(`scopo-aim` = "1sample_sigma")
#   app$click("scopo-nextbtn")
#   app$click("scopo-yesbtn")
#   app$click("scopo-yesbtn")
#   app$upload_file(`dati-file` = "raw_1sample.csv")
#   app$click("dati-nextbtn")
#   app$click("dati-yesbtn")
#   app$click("dati-yesbtn")
#   app$set_inputs(`confronto-parameter` = "load")
#   app$set_inputs(`confronto-1sample_sigma-udm` = "N")
#   app$set_inputs(`confronto-1sample_sigma-label` = "iso")
#   app$set_inputs(`confronto-1sample_sigma-sd` = 0.3)
#   app$click("confronto-1sample_sigma-submit")
#   app$set_inputs(`confronto-1sample_sigma-tabresults` = "Varianze")
#   app$set_inputs(`confronto-1sample_sigma-alternative` = "different", wait_ = FALSE)
#   app$set_inputs(`confronto-1sample_sigma-significance` = "0.95", wait_ = FALSE)
#   app$set_inputs(`confronto-1sample_sigma-alternative` = "greater")
#   app$set_inputs(`confronto-1sample_sigma-significance` = "0.99")
#   app$set_inputs(`confronto-1sample_sigma-alternative` = "different")
#   app$click("confronto-save")
#   app$set_inputs(`confronto-parameter` = "yield")
#   app$set_inputs(`confronto-1sample_sigma-udm` = "kg")
#   app$set_inputs(`confronto-1sample_sigma-label` = "ref")
#   app$set_inputs(`confronto-1sample_sigma-sd` = 20.83)
#   app$click("confronto-1sample_sigma-submit")
#   app$set_inputs(`confronto-1sample_sigma-significance` = "0.95")
#   app$click("confronto-save")
#   app$click("confronto-nextbtn")
#   app$click("confronto-yesbtn")
#   app$click("confronto-yesbtn")
#   app$set_inputs(`report-title` = "My test report for one sample and a population standard deviation")
#   app$set_inputs(`report-description` = "My test setup.")
#   app$set_inputs(`report-discussion` = "Tests passed.")
#   app$expect_values(screenshot_args = FALSE)
#   app$stop()
# })
#
#
# test_that("{shinytest2} recording: SIconfronta_2values_unc", {
#   skip_on_ci()
#   skip_on_covr()
#   skip_on_cran()
#
#   shiny_app <- SIconfronta::run_app()
#
#   app <- AppDriver$new(app_dir = shiny_app,
#                        name = "SIconfronta_2values_unc",
#                        height = 627,
#                        width = 995)
#   app$set_inputs(`scopo-aim` = "2values_unc")
#   app$click("scopo-nextbtn")
#   app$click("scopo-yesbtn")
#   app$click("scopo-yesbtn")
#   app$upload_file(`dati-file` = "raw_2values_unc.csv")
#   app$click("dati-nextbtn")
#   app$click("dati-yesbtn")
#   app$click("dati-yesbtn")
#   app$set_inputs(`confronto-parameter` = "L03")
#   app$set_inputs(`confronto-2values_unc-udm` = "mg/kg")
#   app$click("confronto-save")
#   app$set_inputs(`confronto-parameter` = "L12")
#   app$click("confronto-save")
#   app$click("confronto-nextbtn")
#   app$click("confronto-yesbtn")
#   app$click("confronto-yesbtn")
#   app$set_inputs(`report-title` = "My test report for two values with extended uncertainties")
#   app$set_inputs(`report-description` = "My test setup.")
#   app$set_inputs(`report-discussion` = "Tests passed.")
#   app$expect_values(screenshot_args = FALSE)
#   app$stop()
# })
