---
title: "Esempi di applicazione"
author: "Andrea Bazzano"
date: "2023-08-21"
output: 
  html_document: 
    toc: yes
    toc_float: true
editor_options: 
  markdown: 
    wrap: 72
---

## Esempi di utilizzo dell'applicazione SIprecisa

Nel seguito del documento vengono riportati alcuni esempi di possibili
usi dell'applicazione SIprecisa all'interno di un laboratorio di
analisi chimiche ambientali.

Gli esempi sono suddivisi in base alle opzioni disponibili nella scheda
*Scopo* dell'applicazione e sebbene non rappresentino una casistica
esaustiva, si spera che il lettore possa trovarvi ispirazione per
effettuare confronti in grado di fornire risposte utili e affidabili.

Per ogni opzione è presentato, all'interno di un riquadro blu, un breve
testo generico sul campo di applicazione e un elenco non esaustivo di
possibili esempi. Al di fuori del riquadro, è invece analizzato un
esempio verosimile.

------------------------------------------------------------------------

### Stima di ripetibilità e recupero dalla stessa serie di misure

::: {.minipage style="border:5px solid #2780E3; border-radius: 12px; width: 80%; margin: 25px; padding: 10px"}
In generale, questa opzione è applicabile al caso di una serie di misure tra
loro indipendenti e per i quali siano disponibili i valori delle singole
misure.

Le possibili applicazioni possono riguardare:
-   il calcolo delle ripetibilità e del limite di ripetibilità di un metodo analitico,
    in condizioni ben definite;
-   il calcolo del _bias_ o recupero di un metodo analitico, in condizioni ben definite;
-   la valutazione della presenza di un bias statisticamente significativo.
:::

Mario vuole stimare le prestazioni di precisione e giustezza del suo nuovo
metodo per la determinazione del sifilone nelle acque superficiali.
Ha a disposizione tre campioni di acqua a diversi contenuti noti e certificati di sifilone.

Per ognuno dei tre campioni Mario esegue 10 repliche indipendenti: ogni replica comprende sia
la fase di preparazione, sia la successiva fase di determinazione strumentale.

I valori di riferimento dei tre campioni e le relative incertezze estese sono:

1.   3.032 $\pm$ 0.041 ng/L;
2.   20.43 $\pm$ 0.28 ng/L;
3.   104.3 $\pm$ 1.8 ng/L.

Le misure ottenute per i diversi campioni sono così riassunte:

1.   2.860, 3.113, 2.938, 3.107, 3.071, 2.838, 3.109, 3.088, 3.012, 2.746 ng/L;
2.   19.83, 19.10, 20.25, 20.16, 20.47, 19.12, 20.64, 22.26, 19.29, 21.77 ng/L;
3.   97.66, 107.7, 97.28, 103.3, 95.32, 99.46, 103.1, 110.3, 104.3, 95.49 ng/L.

I valori vengono organizzati nella seguente tabella:

| analita_c    | misura  |
|--------------|---------|
| sifilone_3   | 2.860   |
| sifilone_3   | 3.113   |
| sifilone_3   | 2.938   |
| sifilone_3   | 3.107   |
| sifilone_3   | 3.071   |
| sifilone_3   | 2.838   |
| sifilone_3   | 3.109   |
| sifilone_3   | 3.088   |
| sifilone_3   | 3.012   |
| sifilone_3   | 2.746   |
| sifilone_20  | 19.83   |
| sifilone_20  | 19.10   |
| sifilone_20  | 20.25   |
| sifilone_20  | 20.16   |
| sifilone_20  | 20.47   |
| sifilone_20  | 19.12   |
| sifilone_20  | 20.64   |
| sifilone_20  | 22.26   |
| sifilone_20  | 19.29   |
| sifilone_20  | 21.77   |
| sifilone_100 | 97.66   |
| sifilone_100 | 107.7   |
| sifilone_100 | 97.28   |
| sifilone_100 | 103.3   |
| sifilone_100 | 95.32   |
| sifilone_100 | 99.46   |
| sifilone_100 | 103.1   |
| sifilone_100 | 110.3   |
| sifilone_100 | 104.3   |
| sifilone_100 | 95.49   |

1.  Nella scheda *Scopo* di SIprecisa si seleziona la prima opzione.
2.  Nella scheda *Dati* si seleziona il file con la tabella dei dati in
    formato csv. Si identificano le colonne relative alle informazioni
    sugli analiti e le risposte rispettivamente come "analita_c" e "misura".
3.  Nella scheda *Stime* si seleziona il parametro di interesse, 
    si inserisce l'unità di misura, si seleziona il livello di confidenza 95% 
    e si digita il valore di riferimento comprensivo della sua incertezza estesa.
    Una volta cliccato sul tasto *calcola*, si visualizzano i risultati ottenuti.
4.  Nella scheda *Report* si procede all'eventuale creazione di un
    resoconto in formato pdf.

A titolo di esempio, i risultati riguardanti il sifilone al livello di 
concentrazione di 3 ng/L, evidenziano che:
-   la serie di dati risulta essere distribuita compatibilmente
    a una distribuzione normale ( $W$ = 0.862, $p$-value = 0.0798);
-   la serie di dati risulta essere priva di valori anomali ai livelli di
    confidenza del 95 e 99%;
-   la deviazione standard delle misure risulta essere pari a 0.134 ng/L,
    corrispondente a un coefficiente di variazione del 4.49%.
-   il limite di ripetibilità calcolato dalla serie di misure risulta essere
    pari 0.429 ng/L al livello di confidenza del 95%, corrispondente a un valore
    relativo pari al 14.4%.
-   la media delle misure risulta essere 2.99 ng/L con un intervallo di confidenza
    al livello del 95% pari 2.89 - 3.08 ng/L.
-   il recupero risulta pari al 98.6% e il _bias_ è -0.0438 ng/L o -1.47% rispetto
    al valore di riferimento. Tale _bias_, secondo il calcolo dell' $E_n$ risulta
    essere non significativo ( $E_n$ sperimentale = 0.4199).

Anche le prestazioni calcolate per i restanti due livelli di concentrazione di
20 e 100 ng/L, evidenziano dati distribuiti normalmente con assenza di valori
anomali, coefficienti di variazione prossimi al 5% e limiti di ripetibilità 
relativi intorno al 16%, mentre il recupero si attesta sempre al di sopra del 95%,
con un _bias_ relativo assoluto inferiore al 3% e non statisticamente signigicativo
rispetto al valore di riferimento.

Mario è soddisfatto ma, per poter affermare che il suo metodo è adatto alla
determinazione del sifilone nelle acque superficiali, dovrà confrontare le 
prestazioni da lui ottenute con i requisiti del metodo... ma questa è un'altra storia.

------------------------------------------------------------------------

### Stima della ripetibilità da una serie di misure in doppio

::: {.minipage style="border:5px solid #2780E3; border-radius: 12px; width: 80%; margin: 25px; padding: 10px"}

Questa opzione si applica nel caso di serie di misure duplicate, anche eseguite
su campioni reali con diverse concentrazioni medie.

Le possibili applicazioni possono riguardare:
-   il calcolo delle ripetibilità relativa e del limite di ripetibilità relativa
    di un metodo analitico;
-   la stima della componente casuale dell'incertezza di misura, secondo quanto
    previsto nella norma [UNI ISO 11352:2012. Water quality - 
    Estimation of measurement uncertainty based on validation and quality 
    control data](https://store.uni.com/iso-11352-2012).
:::

Peppina è diffidente e si chiede se la precisione determinata in passato da 
Mario su acque con valori certificati di sifilone, sia simile a quella 
determinabile su campioni reali.

Peppina ha eseguito per un anno la determinazione del contenuto di sifilone
nelle acque superficiali e, una volta al mese, ha sottoposto ad analisi in
duplicato uno dei campioni.

La tabella dei dati viene così organizzata:

| analita  | misura1 | misura2 |
|----------|---------|---------|
| sifilone | 3.220   | 2.896   |
| sifilone | 4.738   | 4.293   |
| sifilone | 9.909   | 10.43   |
| sifilone | 22.35   | 21.95   |
| sifilone | 35.50   | 35.46   |
| sifilone | 42.65   | 37.47   |
| sifilone | 52.90   | 49.84   |
| sifilone | 56.83   | 53.67   |
| sifilone | 76.97   | 78.89   |
| sifilone | 74.35   | 79.46   |
| sifilone | 112.2   | 110.2   |
| sifilone | 113.6   | 115.9   |

1.  Nella scheda *Scopo* di SIprecisa si seleziona la seconda opzione.
2.  Nella scheda *Dati* si seleziona il file con la tabella dei dati in
    formato csv. Si identificano le colonne relative alle informazioni
    sugli analiti e le due risposte rispettivamente come "analita",
    "misura1" e "misura2".
3.  Nella scheda *Stime* si seleziona il parametro di interesse, 
    si inserisce l'unità di misura e si seleziona il livello di confidenza 95%.
    Spostandosi tra le schede nelle sezione di destra, si visualizzano i risultati.
4.  nella scheda *Report* si procede all'eventuale creazione di un
    resoconto in formato pdf.

Le differenze relative tra le due misure risultano essere compatibili con una
distribuzione normale ( $W$ = 0.958, $p$-value = 0.7585) e non vengono rilevati
outliers al livello di confidenza del 95 e 99%.

Il coefficiente di variazione e il limite di ripetibilità relativo risultano
essere rispettivamente pari al 4.80% e 14.9%.

A Peppina tocca buttare giù un boccone amaro: nonostante i dati da lei raccolti
derivino da un esperimento protratto nel tempo e quindi producano una stima della
precisione in condizioni di ripetibilità intermedia, il coefficiente di variazione
ottenuto è praticamente uguale a quello stimato da Mario in condizioni di
ripetibilità ristretta. Peppina conclude che il contributo alla precisione dovuto
alle variazioni di matrice dei campioni reali, nonché alle variazioni temporali
avvenute nel corso di un anno, sono trascurabili.

------------------------------------------------------------------------

### Stima del recupero da un valore singolo

::: {.minipage style="border:5px solid #2780E3; border-radius: 12px; width: 80%; margin: 25px; padding: 10px"}
In questa opzione, una misura dotata di incertezza estesa viene paragonata
a un valore certificato.

Alcuni esempi di applicazioni possono riguardare:

-   valutare il recupero e il _bias_ in condizioni in cui risulti difficoltoso
    effettuare misure ripetute con un idoneo materiale di riferimento certificato;
-   valutare il grado di concordanza tra una misura e i valore assegnato in un
    circuito interlaboratorio, tenendo conto anche dell'incertezza di quest'ultimo
    valore.
:::

Rosalia è conosciuta in paese per essere tirchia e per la sua antipatia verso
Mario: il chimico più famoso del condominio in cui entrambi abitano.

Per screditare il suo rivale, Rosalia decide quindi di acquistare una matrice 
di acqua certificata con un contenuto di sifilone pari a 35.62 $\pm$ 0.71 ng/L ma,
volendo risparmiare, sceglie il materiale con un volume appena sufficiente a fare
una sola misura. Mario analizza l'acqua di Rosalia credendo sia un semplice
campione incognito.

Il risultato ottenuto è 34.91 $\pm$ 4.19 ng/L di sifilone.

Rosalia predispone la seguente tabella:

| analita  | valore   | incertezza_estesa |
|----------|----------|-------------------|
| sifilone | 34.91    | 4.19              |

1.  Nella scheda *Scopo* di SIprecisa seleziona la terza opzione.
2.  Nella scheda *Dati* seleziona il file con la tabella dei dati in
    formato csv. Identifica le colonne relative alle informazioni sugli
    analiti, risposte e incertezze estese rispettivamente come "analita", "valore"
    e "incertezza_estesa".
3.  Nella scheda *Stime* si seleziona il parametro di interesse, 
    si inserisce l'unità di misura
    e si digita il valore di riferimento comprensivo della sua incertezza estesa.
    Una volta cliccato sul tasto *calcola*, si visualizzano i risultati ottenuti.
4.  Nella scheda *Report* procede all'eventuale creazione di un
    resoconto in formato pdf.

Rosalia si deve ricredere: il valore misurato da Mario risulta avere un recupero
del 98% e un _bias_ di -0.710 ng/L, pari al -2.03% del valore di sifilone
certificato.
Il calcolo dell'errore normalizzato conferma l'assenza di un _bias_ statisticamente
significativo ( $E_n$ = 0.1671).
