---
title: "Validazione dei risultati"
author: "Andrea Bazzano"
date: "2023-08-10"
output: 
  html_document: 
    toc: yes
    toc_float: true
---

## Verifiche eseguite nella fase di validazione dell'applicazione SIprecisa

### Verifica per il test di normalità di Shapiro-Wilk

Dati da Shapiro S. S., Wilk M. B., An analysis of variance test for normality (complete samples). Biometrika (1965), 52, 3 and 2, p. 591. Section 4 - Examples, pag. 606, Example 1. (<http://links.jstor.org/sici?sici=0006-3444%28196512%2952%3A3%2F4%3C591%3AAAOVTF%3E2.0.CO%3B2-B>).

#### Input

-   valori: 148, 154, 158, 160, 161, 162, 166, 170, 182, 195, 236.

#### Valori attesi

-   W = 0.79;
-   p-value \< 0.01;
-   esito = I valori non sono compatibili con una distribuzione normale.

### Verifica per il test sui possibili valori anomali (GESD)

Dati da Tietjen G. L., Moore R. H., Some Grubbs-Type Statistics for the Detection of Several Outliers. Technometrics (1972), 14, 3, pp. 583-597 (<https://www.itl.nist.gov/div898/handbook/eda/section3/eda35h1.htm>).

#### Input

-   Valori: 199.31, 199.53, 200.19, 200.82, 201.92, 201.95, 202.18, 245.57;
-   livello di significatività: 0.99.

#### Valori attesi

-   outliers: 245.57.


### Verifica per il test sul confronto tra la media di una serie di dati e un valore di riferimento

Dati da UNI ISO 2854:1988, prospetto A', (pag. 37).

#### Input

-   Valori:

| parameter | load  |
|-----------|-------|
| yarns     | 2.297 |
| yarns     | 2.582 |
| yarns     | 1.949 |
| yarns     | 2.362 |
| yarns     | 2.040 |
| yarns     | 2.133 |
| yarns     | 1.855 |
| yarns     | 1.986 |
| yarns     | 1.642 |
| yarns     | 2.915 |

-   valore di riferimento: 2.40;
-   ipotesi alternativa: valore di riferimento $\neq$ media delle misure;
-   livello di significatività: 0.95.

#### Valori attesi

-   differenza tra le medie: 2.176 (1.909, 2.443);
-   gradi di libertà: 9;
-   $\alpha$: 0.975;
-   $t$ calcolato: 1.8950;
-   $t$ critico: 2.2622;
-   $p$-value: 0.0906;
-   esito: il bias delle misure rispetto al valore di riferimento non è statisticamente significativo.

------------------------------------------------------------------------

Dati da UNI ISO 2854:1988, prospetto B', (pag. 37).

#### Input

-   Valori: come nella sezione precedente;
-   valore di riferimento: 2.40;
-   ipotesi alternativa: valore di riferimento $\neq$ media delle misure;
-   livello di significatività: 0.99.

#### Valori attesi

-   differenza tra le medie: 2.176 (1.792, 2.560);
-   gradi di libertà: 9;
-   $\alpha$: 0.995;
-   $t$ calcolato: 1.8950;
-   $t$ critico: 3.2498;
-   $p$-value: 0.0906;
-   esito: il bias delle misure rispetto al valore di riferimento non è statisticamente significativo.

### Verifica per il test sul confronto tra due valori dotati di incertezza estesa

Dati da ISO 13528:2022(E) Sezione E4.

#### Input

-   Misure:

| reference | value | uncertainty |
|-----------|-------|-------------|
| en        | 0.037 | 0.013       |

- Valore di riferimento: 0.044;
- Incertezza estesa del valore di riferimento: 0.0082.

#### Valori attesi

-   ipotesi alternativa: valore di riferimento $\neq$ valore misurato;
-   differenza tra i valori: 0.007000 (-0.008370, 0.02237);
-   $E_n$ calcolato: 0.4554;
-   $E_n$ critico: 1.000;
-   esito: il valore di riferimento e il valore misurato non sono statisticamente differenti.

------------------------------------------------------------------------

Dati da ISO 13528:2022(E) Sezione E4.

#### Input

-   Misure:

| reference | value  | uncertainty |
|-----------|--------|-------------|
| en        | 0.0239 | 0.0036      |

- Valore di riferimento: 0.044;
- Incertezza estesa del valore di riferimento: 0.0082.

#### Valori attesi

-   ipotesi alternativa: valore di riferimento $\neq$ valore misurato;
-   differenza tra i valori: 0.02010 (0.01114, 0.02906);
-   $E_n$ calcolato: 2.244;
-   $E_n$ critico: 1.000;
-   esito: il valore di riferimento e il valore misurato sono statisticamente differenti.

### Verifica per il corretto calcolo dei parametri di precisione da una serie di misure indipendenti

Dati da ISO 11352:2012(E), Annex B, Table B.1.

#### Input

- Misure: 2.16, 2.40, 2.31, 2.33, 2.36, 2.27, 2.37, 2.27, 2.27, 2.10, 2.26, 2.58,
          2.23, 2.47, 2.37, 2.39, 2.30, 2.26, 2.42, 2.67, 2.36, 2.37, 2.36, 2.30,
          2.50, 2.17, 2.43, 2.35, 2.16, 2.30.
- livello di significatività: 0.950

#### Valori attesi

- deviazione standard: 0.122;
- deviazione standard relativa: 5.21%;
- limite di ripetibilità: 0.352 (non riportato nel riferimento);
- limite di ripetibilità relativo: 15.1% (non riportato nel riferimento).

### Verifica per il corretto calcolo dei parametri di precisione da una serie di misure duplicate

Dati da ISO 11352:2012(E), Annex B, Table B.4.

#### Input

- Differenze relative tra coppie di misure: 0.1544, 0.1689, 0.1046, 0.0445,
                                            0.1162, 0.0303, 0.1135, 0.0250,
                                            0.0501, 0.0255
- livello di significatività: 0.950

#### Valori attesi

- valore medio: 0.0833;
- deviazione standard relativa: 7.38%;
- limite di ripetibilità relativo: 23.6% (non riportato nel riferimento).

### Verifica per il corretto calcolo dei parametri di giustezza da una serie di misure indipendenti

Dati da ISO 5725-4, Annex B, Table B.3, content level 3.

#### Input

- Misure: 0.4143, 0.4006, 0.4004, 0.4072, 0.3959, 0.4049, 0.3850, 0.3947,
          0.4023, 0.4043, 0.4077, 0.4077
- valore di riferimento: 0.403;
- livello di significatività: 0.950

#### Valori attesi

- Valore medio: 0.4021;
- bias: -0.00092;
- bias relativo: -0.23% (non riportato nel riferimento);
- recupero: 99.8% (non riportato nel riferimento).
