# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [stable, main, master]
  release:
    types: [published]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup Latex
        uses: r-lib/actions/setup-tinytex@v2

      - name: Latex Version
        run: tlmgr --version

      - name: Install additional LaTeX packages
        run: |
          tlmgr install babel-italian
          tlmgr install microtype
          tlmgr install tex-gyre
          tlmgr install fancyhdr
          tlmgr install lastpage
          tlmgr install booktabs
          tlmgr install koma-script
          tlmgr install hyphen-italian
          tlmgr list --only-installed

      - name: Setup R
        uses: r-lib/actions/setup-r@v2-branch
        with:
          working-directory: './SIprecisa'
          r-version: 'renv'
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: install packages listed by renv
        uses: r-lib/actions/setup-renv@v2
        with:
          working-directory: './SIprecisa'

      - name: Checking the package
        uses: r-lib/actions/check-r-package@v2
        with:
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
          working-directory: './SIprecisa'
